version: 0.2

phases:
   install:
      runtime: - versions:
      nodejs: 14
      commands:
         - echo Installing dependency...
   pre_build:
      commands:
         - npm install
   build:
      commands:
         - echo Build completed on `date`
         - echo Compiling the Node.js cod
         - npm run build
   post_build:
      commands:
         - echo Build completed on `date`
artifacts:
   files:
      - "public/**/*"
      - ".next/*"
      - "package.json"
      - "node_modules"
