version: 0.2

phases:
   install:
      nodejs: 14
      commands:
         - echo Installing dependency...
   pre_build:
      commands:
         - npm install
   build:
      commands:
         - echo Build completed on `date`
         - echo Compiling the Node.js code
         - npm run build
   post_build:
      commands:
         - echo Build completed on `date`
artifacts:
   files:
      - "**/*"
